FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY services/auth_service/requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# Copy all project code into the container
COPY . .

# Command to run the API using the PORT variable
# The PORT will be passed in by the environment (docker-compose or Render)
CMD uvicorn services.auth_service.main:app --host 0.0.0.0 --port $PORT
